# Generated by Django 3.2 on 2021-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='posting_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='performance_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
