# Generated by Django 3.2 on 2021-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='performance_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
