# Generated by Django 3.2 on 2021-06-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_performance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-performance_date']},
        ),
    ]
