# Generated by Django 3.2 on 2021-06-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links_and_text', models.TextField()),
                ('docs', models.FileField(upload_to='')),
            ],
        ),
    ]
